// <auto-generated />
using McpFinanceExpenseApi.Models.Enums;

namespace McpFinanceExpenseApi.Models;

public record GetExpenseResponseDto(
    int EmployeeId,
    string Description,
    decimal Amount,
    string Currency,
    ExpenseStatusType Status
    );